import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../../.env') });

import { connectMongoDB } from '../config/db.js';
import { MenuItem } from '../models/MenuItem.js';
import { db } from '../data/db.js';

// Import the 22 mock menu items
const seedDishes = [
  {
    id: 'food-001',
    itemId: 'food-001',
    categoryId: 'starters',
    category: 'Starters',
    name: 'Paneer Tikka',
    description: 'Fresh cottage cheese cubes marinated in spiced yogurt and grilled in traditional clay oven with bell peppers and onions.',
    price: 220,
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.8,
    preparationTime: '15 mins',
    addons: [
      { id: 'addon-cheese', name: 'Extra Cheese Dip', price: 40 },
      { id: 'addon-mint', name: 'Extra Mint Chutney', price: 20 },
      { id: 'addon-paneer', name: 'Extra Paneer Cubes (2 pcs)', price: 60 },
    ],
  },
  {
    id: 'food-002',
    itemId: 'food-002',
    categoryId: 'starters',
    category: 'Starters',
    name: 'Chicken Wings (Peri-Peri)',
    description: 'Crispy fried chicken wings tossed in fiery peri-peri garlic glaze, served with creamy ranch dip.',
    price: 240,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '18 mins',
    addons: [
      { id: 'addon-sauce', name: 'Extra Peri-Peri Sauce', price: 25 },
      { id: 'addon-ranch', name: 'Extra Ranch Dip', price: 30 },
      { id: 'addon-fries', name: 'Side of Seasoned Fries', price: 70 },
    ],
  },
  {
    id: 'food-003',
    itemId: 'food-003',
    categoryId: 'starters',
    category: 'Starters',
    name: 'Veg Spring Rolls',
    description: 'Golden fried crispy rolls stuffed with shredded vegetables and glass noodles, served with sweet chili dip.',
    price: 180,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: false,
    rating: 4.5,
    preparationTime: '12 mins',
    addons: [
      { id: 'addon-sweetchili', name: 'Extra Sweet Chili Sauce', price: 20 },
      { id: 'addon-mayo', name: 'Garlic Mayo Dip', price: 25 },
    ],
  },
  {
    id: 'food-004',
    itemId: 'food-004',
    categoryId: 'starters',
    category: 'Starters',
    name: 'Mutton Seekh Kebab',
    description: 'Minced lamb skewers blended with aromatic spices and herbs, char-grilled to juicy perfection.',
    price: 340,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '20 mins',
    addons: [
      { id: 'addon-rumali', name: 'Add Rumali Roti (1 pc)', price: 30 },
      { id: 'addon-salad', name: 'Extra Lachha Onion Salad', price: 20 },
    ],
  },
  {
    id: 'food-005',
    itemId: 'food-005',
    categoryId: 'starters',
    category: 'Starters',
    name: 'Crispy Corn Chilli Pepper',
    description: 'Golden sweet corn kernels tossed with crunchy bell peppers, spring onion, and crushed black pepper.',
    price: 240,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=500&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.6,
    preparationTime: '15 mins',
    addons: [{ id: 'addon-extra-lemon', name: 'Extra Lemon Butter', price: 20 }],
  },
  {
    id: 'food-006',
    itemId: 'food-006',
    categoryId: 'main-course',
    category: 'Main Course',
    name: 'Butter Chicken (Murgh Makhani)',
    description: 'Tender tandoori chicken cooked in a rich, buttery tomato gravy infused with fenugreek leaves and fresh cream.',
    price: 320,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '20 mins',
    addons: [
      { id: 'addon-cream', name: 'Extra Cream & Butter Topping', price: 30 },
      { id: 'addon-chicken', name: 'Boneless Chicken Upgrade', price: 50 },
    ],
  },
  {
    id: 'food-007',
    itemId: 'food-007',
    categoryId: 'main-course',
    category: 'Main Course',
    name: 'Paneer Butter Masala',
    description: 'Soft cottage cheese cubes cooked in a silky, mildly spiced creamy tomato gravy.',
    price: 280,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.7,
    preparationTime: '18 mins',
    addons: [
      { id: 'addon-cheese', name: 'Grated Cheese Topping', price: 40 },
      { id: 'addon-paneer-more', name: 'Extra Paneer Portions', price: 60 },
    ],
  },
  {
    id: 'food-008',
    itemId: 'food-008',
    categoryId: 'main-course',
    category: 'Main Course',
    name: 'Dal Makhani',
    description: 'Slow-simmered black lentils cooked overnight with butter, cream, and subtle whole spices.',
    price: 240,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.8,
    preparationTime: '15 mins',
    addons: [{ id: 'addon-butter', name: 'Extra Desi Ghee Dollop', price: 25 }],
  },
  {
    id: 'food-009',
    itemId: 'food-009',
    categoryId: 'main-course',
    category: 'Main Course',
    name: 'Kadhai Chicken',
    description: 'Chicken cooked with freshly ground coriander and red chilies in a spicy bell pepper gravy.',
    price: 310,
    image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: false,
    rating: 4.6,
    preparationTime: '20 mins',
    addons: [{ id: 'addon-spicy', name: 'Extra Spicy Guntur Tadka', price: 20 }],
  },
  {
    id: 'food-010',
    itemId: 'food-010',
    categoryId: 'chinese',
    category: 'Chinese',
    name: 'Chilli Chicken Gravy',
    description: 'Boneless chicken cubes tossed with diced bell peppers, spring onions, green chilies, and dark soy sauce.',
    price: 260,
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.7,
    preparationTime: '15 mins',
    addons: [{ id: 'addon-gravy', name: 'Extra Garlic Soy Gravy', price: 30 }],
  },
  {
    id: 'food-011',
    itemId: 'food-011',
    categoryId: 'chinese',
    category: 'Chinese',
    name: 'Veg Hakka Noodles',
    description: 'Wok-tossed noodles with shredded cabbage, carrots, bell peppers, and scallions in light soy seasoning.',
    price: 200,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.5,
    preparationTime: '12 mins',
    addons: [{ id: 'addon-schezwan', name: 'Schezwan Sauce Dip', price: 25 }],
  },
  {
    id: 'food-012',
    itemId: 'food-012',
    categoryId: 'chinese',
    category: 'Chinese',
    name: 'Chicken Fried Rice',
    description: 'Fluffy long-grain rice stir-fried with diced chicken, eggs, and garden vegetables with toasted sesame aroma.',
    price: 230,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: false,
    rating: 4.6,
    preparationTime: '14 mins',
    addons: [{ id: 'addon-fried-egg', name: 'Extra Fried Egg', price: 30 }],
  },
  {
    id: 'food-013',
    itemId: 'food-013',
    categoryId: 'breads',
    category: 'Breads',
    name: 'Butter Naan',
    description: 'Traditional leavened flatbread baked in tandoor, brushed with pure butter.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1533450718592-29d45635f0a9?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.8,
    preparationTime: '8 mins',
    addons: [],
  },
  {
    id: 'food-014',
    itemId: 'food-014',
    categoryId: 'breads',
    category: 'Breads',
    name: 'Garlic Naan',
    description: 'Leavened flatbread topped with minced roasted garlic and fresh coriander, brushed with butter.',
    price: 65,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '10 mins',
    addons: [{ id: 'addon-cheese', name: 'Cheese Stuffed Upgrade', price: 40 }],
  },
  {
    id: 'food-015',
    itemId: 'food-015',
    categoryId: 'breads',
    category: 'Breads',
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked crisp in tandoor oven.',
    price: 25,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: false,
    rating: 4.6,
    preparationTime: '6 mins',
    addons: [{ id: 'addon-butter-roti', name: 'Add Desi Butter', price: 10 }],
  },
  {
    id: 'food-016',
    itemId: 'food-016',
    categoryId: 'rice',
    category: 'Rice & Biryani',
    name: 'Dum Chicken Biryani',
    description: 'Aromatic basmati rice layered with spiced marinated chicken and slow-cooked in handi, served with mirchi salan and raita.',
    price: 320,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isVeg: false,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '20 mins',
    addons: [
      { id: 'addon-raita', name: 'Extra Boondi Raita', price: 30 },
      { id: 'addon-salan', name: 'Extra Mirchi Ka Salan', price: 35 },
    ],
  },
  {
    id: 'food-017',
    itemId: 'food-017',
    categoryId: 'rice',
    category: 'Rice & Biryani',
    name: 'Veg Dum Biryani',
    description: 'Fragrant basmati rice cooked with fresh seasonal vegetables, mint, saffron, and rich biryani spices.',
    price: 260,
    image: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.7,
    preparationTime: '18 mins',
    addons: [{ id: 'addon-raita', name: 'Extra Cucumber Raita', price: 30 }],
  },
  {
    id: 'food-018',
    itemId: 'food-018',
    categoryId: 'rice',
    category: 'Rice & Biryani',
    name: 'Jeera Rice',
    description: 'Long grain basmati rice tempered with aromatic cumin seeds and fresh ghee.',
    price: 150,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: false,
    rating: 4.5,
    preparationTime: '10 mins',
    addons: [],
  },
  {
    id: 'food-019',
    itemId: 'food-019',
    categoryId: 'beverages',
    category: 'Beverages',
    name: 'Cold Coffee with Ice Cream',
    description: 'Thick creamy blended cold coffee topped with a generous scoop of vanilla ice cream and chocolate drizzle.',
    price: 130,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.8,
    preparationTime: '8 mins',
    addons: [{ id: 'addon-choco', name: 'Extra Choco Chips & Fudge', price: 25 }],
  },
  {
    id: 'food-020',
    itemId: 'food-020',
    categoryId: 'beverages',
    category: 'Beverages',
    name: 'Fresh Lime Soda',
    description: 'Fizzy refreshing cooler prepared with fresh lemon juice, mint, and choice of sweet or salted soda.',
    price: 80,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: false,
    rating: 4.5,
    preparationTime: '5 mins',
    addons: [{ id: 'addon-mint', name: 'Extra Mint Muddle', price: 15 }],
  },
  {
    id: 'food-021',
    itemId: 'food-021',
    categoryId: 'desserts',
    category: 'Desserts',
    name: 'Gulab Jamun with Rabri',
    description: 'Hot melt-in-mouth milk dumplings served soaked in saffron rose syrup, paired with chilled rich rabri.',
    price: 120,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '8 mins',
    addons: [{ id: 'addon-nuts', name: 'Extra Roasted Pistachios & Almonds', price: 30 }],
  },
  {
    id: 'food-022',
    itemId: 'food-022',
    categoryId: 'desserts',
    category: 'Desserts',
    name: 'Rasmalai (2 pcs)',
    description: 'Spongy soft cottage cheese discs soaked in cardamom flavored saffron sweetened thickened milk.',
    price: 130,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isVeg: true,
    isAvailable: true,
    isRecommended: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '6 mins',
    addons: [{ id: 'addon-kesar', name: 'Extra Saffron Milk Drizzle', price: 25 }],
  },
];

async function seed() {
  await connectMongoDB();
  console.log('🔄 Connected to MongoDB. Seeding all 22 menu items...');

  // Clear existing items in MongoDB Atlas
  await MenuItem.deleteMany({});

  // Insert all 22 items
  const docs = await MenuItem.insertMany(seedDishes);
  console.log(`✅ Successfully seeded ${docs.length} menu items into MongoDB Atlas!`);

  // Update local db.json
  db.set('menuItems', seedDishes);
  console.log(`✅ Updated local db.json with all ${seedDishes.length} menu items!`);

  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seeding error:', err);
  process.exit(1);
});
